name: main
on:
  issues:
  workflow_dispatch:
  push:
    paths: .github/workflows/main.yml

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
    - name: Check out the Git repository and its main branch (not detached HEAD)
      uses: actions/checkout@v3
      with:
        ref: main
        fetch-depth: 0
    - name: Fetch GitHub Issues and store them in Git notes
      run: |
        # Make the shell show commands as they are executed
        set -x

        # Configure GitHub Actions service account Git identity
        git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
        git config --global user.name "github-actions[bot]"

        # Pull existing notes so they are built upon not instead of for the push
        git fetch origin "refs/notes/*:refs/notes/*"

        # Store the GitHub Issues in a Git note associated to the main branch
        git notes add main -m "$(curl ${{github.api_url}}/repos/${{github.repository}}/issues -u :${{github.token}})"

        # Print Git notes for each commit on main (like `git status` for notes)
        git log --pretty=format:"%ai%n  ${{github.server_url}}/${{github.repository}}/commit/%h%n  %s%n  %N%n" --show-notes main

        # Configure the GitHub remote for the Git repository
        git remote set-url origin https://:${{github.token}}@github.com/${{github.repository}}

        # Push the changes to the Git notes back to the GitHub repository
        git push origin refs/notes/*
