name: main
on:
  issues:
  workflow_dispatch:
  push:
    paths: .github/workflows/main.yml

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
    - name: Check out the Git repository and its main branch (not detached HEAD)
      uses: actions/checkout@v3
      with:
        ref: main
        fetch-depth: 0
    - name: Fetch GitHub Issues and store them in Git notes
      uses: tomashubelbauer/github-issues-git-notes@main
    - name: Print the Git notes for verification
      run: git log --pretty=format:"%ai%n %H%n %s%n %N%n" --show-notes main
