name: main
on:
  issues:
  issue_comment:
  workflow_dispatch:
  push:
    paths: .github/workflows/main.yml

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
    - name: Fetch GitHub Issues and store them in Git notes
      uses: tomashubelbauer/github-issues-git-notes@main
    - name: Check out the Git repository and its main branch (not detached HEAD)
      uses: actions/checkout@v3
      with:
        ref: main
        fetch-depth: 0
    - name: Print the Git notes for verification
      run: |
        export TZ=UTC
        git log --pretty=format:"%ai ${{github.server_url}}/${{github.repository}}/commit/%h %<(80,trunc)%s%n%N%n" --show-notes main
